name: MultiPack
version: ${project.version}-${BUILD_NUMBER}
description: Allowes setting of a texture pack in WorldGuard regions, or a world.
authors: [nala3]

main: net.worldoftomorrow.MultiPack.MultiPack
database: false
depend: [WorldGuard]

commands:
    multipack:
        description: The base multipack command
        usage: /multipack <add|remove|set|reload> <world> <region> <url>